export const skillData = [
    {
        name:"Html",
        image:"/skills/html.svg"
    },
    {
        name:"Css",
        image:"/skills/css.svg"
    },
    {
        name:"Javascript",
        image:"/skills/javascript.svg"
    },
    {
        name:"React",
        image:"/skills/react.svg"
    },
    {
        name:"Nextjs",
        image:"/skills/nextjs.svg"
    },
    {
        name:"Nodejs",
        image:"/skills/nodejs.svg"
    },
    {
        name:"Typecript",
        image:"/skills/typescript.svg"
    },
    {
        name:"Expressjs",
        image:"/skills/expressjs.svg"
    },
    {
        name:"Git",
        image:"/skills/git.svg"
    },
    {
        name:"Java",
        image:"/skills/java.svg"
    },
    {
        name:"MongoDB",
        image:"/skills/mongodb.svg"
    },
    {
        name:"PostgreSQL",
        image:"/skills/postgresql.svg"
    },
    {
        name:"Rust",
        image:"/skills/rust.svg"
    },
    {
        name:"Tailwindcss",
        image:"/skills/tailwindcss.svg"
    },
    {
        name:"Firebase",
        image:"/skills/firebase.svg"
    },
    {
        name:"Zustand",
        image:"/skills/zustand.svg"
    }
]